import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const PRESETS_PATH = join(process.cwd(), "config", "presets.json");
const OUT_DIR = join(process.cwd(), "tests", "helpers");
const OUT_FILE = join(OUT_DIR, "preset-keys.generated.ts");

function main() {
  const raw = JSON.parse(readFileSync(PRESETS_PATH, "utf-8"));
  const names = Object.keys(raw).sort();

  const content =
    `// AUTO-GENERATED by scripts/gen-preset-keys.ts\n` +
    `export const PRESET_KEYS = [\n` +
    names.map((n) => `  \"${n}\",`).join("\n") +
    `\n] as const;\n\nexport type PresetName = (typeof PRESET_KEYS)[number];\n`;

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_FILE, content, "utf-8");
  console.log(`Generated ${OUT_FILE} with ${names.length} presets`);
}

main();
