import { readdirSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const USERS_DIR = join(process.cwd(), "data", "trails", "users");
const OUT_DIR = join(process.cwd(), "tests", "helpers");
const OUT_FILE = join(OUT_DIR, "user-keys.generated.ts");

function main() {
  const files = readdirSync(USERS_DIR).filter(
    (f) => f.startsWith("trails_user_") && f.endsWith(".json")
  );
  const keys = files
    .map((f) => f.replace("trails_", "").replace(".json", ""))
    .sort();

  const content =
    `// AUTO-GENERATED by scripts/gen-user-keys.ts. Do not edit manually.\n` +
    `export const USER_KEYS = [\n` +
    keys.map((k) => `  \"${k}\",`).join("\n") +
    `\n] as const;\n\nexport type UserKey = (typeof USER_KEYS)[number];\n`;

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_FILE, content, "utf-8");
  console.log(`Generated ${OUT_FILE} with ${keys.length} keys`);
}

main();
