import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { PRESETS_PATH } from "../src/config.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const OUT_DIR = join(__dirname, "..", "tests", "helpers");
const OUT_FILE = join(OUT_DIR, "preset-keys.generated.ts");

function main() {
  const raw = JSON.parse(readFileSync(PRESETS_PATH, "utf-8"));
  const names = Object.keys(raw)
    .map((k) => k.toUpperCase())
    .sort();

  const content =
    `// AUTO-GENERATED by scripts/gen-preset-keys.ts\n` +
    `export const PRESET_KEYS = [\n` +
    names.map((n) => `  "${n}",`).join("\n") +
    `\n] as const;\n\nexport type PresetName = (typeof PRESET_KEYS)[number];\n`;

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_FILE, content, "utf-8");
  console.log(`Generated ${OUT_FILE} with ${names.length} presets`);
}

main();
