#!/usr/bin/env tsx

// Set dummy env to bypass validation (only for graph visualization)
process.env.REDIS_HOST ??= "localhost";
process.env.REDIS_PORT ??= "6379";
process.env.CORE_API_URL ??= "http://localhost:3000";
process.env.POSTGRES_HOST ??= "localhost";
process.env.POSTGRES_PORT ??= "5432";
process.env.POSTGRES_USER ??= "postgres";
process.env.POSTGRES_PASSWORD ??= "postgres";
process.env.POSTGRES_DB ??= "postgres";
process.env.OPENAI_API_KEY ??= "sk-dummy";

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

type GraphModule = {
  createGraphBuilder: () => {
    compile: (options: { checkpointer: false }) => {
      getGraph: () => { drawMermaid: (options: { withStyles: boolean }) => string };
    };
  };
};

type GraphConfig = {
  name: string;
  importPath: string;
};

const GRAPHS: GraphConfig[] = [
  { name: "cold-start-v2", importPath: "../src/facade/langGraph/cold-start-v2/cold-start-graph.js" },
  { name: "search-graph", importPath: "../src/facade/langGraph/search-graph/search-graph.js" },
  { name: "upsert-context", importPath: "../src/facade/langGraph/upsert-context/upsert-context-graph.js" },
  { name: "upsert-trail", importPath: "../src/facade/langGraph/upsert-trail/upsert-trail-graph.js" },
  { name: "update-context", importPath: "../src/facade/langGraph/update-context/update-context-graph.js" },
];

async function loadGraphModule(importPath: string): Promise<GraphModule> {
  return import(importPath);
}

const OUTPUT_DIR = "docs/graphs";

async function exportGraph(config: GraphConfig): Promise<void> {
  const graphModule = await loadGraphModule(config.importPath);
  const builder = graphModule.createGraphBuilder();
  const compiled = builder.compile({ checkpointer: false });
  const graph = compiled.getGraph();
  const mermaid = graph.drawMermaid({ withStyles: true });

  const markdown = `# ${config.name}

LangGraph workflow visualization.

\`\`\`mermaid
${mermaid}\`\`\`

Generated by \`npm run graph\`. View interactively at [mermaid.live](https://mermaid.live).
`;

  const outputPath = path.join(OUTPUT_DIR, `${config.name}.md`);
  writeFileSync(outputPath, markdown);
  console.log(`  ${config.name}.md`);
}

async function main(): Promise<void> {
  console.log(`\nExporting ${GRAPHS.length} LangGraph graphs to ${OUTPUT_DIR}/\n`);

  if (!existsSync(OUTPUT_DIR)) {
    mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  for (const config of GRAPHS) {
    await exportGraph(config);
  }

  console.log(`\n Done! View graphs in docs/graphs/ or at https://mermaid.live\n`);
}

await main();
