#!/usr/bin/env tsx
// @ts-nocheck

// Set dummy env to bypass validation (only for graph visualization)
process.env.REDIS_HOST ??= "localhost";
process.env.REDIS_PORT ??= "6379";
process.env.CORE_API_URL ??= "http://localhost:3000";
process.env.POSTGRES_HOST ??= "localhost";
process.env.POSTGRES_PORT ??= "5432";
process.env.POSTGRES_USER ??= "postgres";
process.env.POSTGRES_PASSWORD ??= "postgres";
process.env.POSTGRES_DB ??= "postgres";
process.env.OPENAI_API_KEY ??= "sk-dummy";

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

type GraphModule = {
  createGraphBuilder: () => {
    compile: (options: { checkpointer: false }) => {
      getGraph: () => { drawMermaid: (options: { withStyles: boolean }) => string };
    };
  };
};

type GraphConfig = {
  name: string;
  importPath: string;
  title: string;
  description: string;
  labels?: Record<string, string>;
};

const GRAPHS: GraphConfig[] = [
  {
    name: "cold-start",
    importPath: "../src/facade/langGraph/cold-start-v2/cold-start-graph.js",
    title: "Cold Start: Career Story Collection",
    description:
      "Multi-turn dialogue for collecting user's career history. Guides through story → plan → context extraction → validation → save.",
    labels: {
      __start__: "Start",
      __end__: "End",
      gather_story: "Collect Story",
      parse_story_decision: "Analyze Response",
      plan_career: "Plan Career Path",
      show_plan: "Show Plan",
      parse_plan_decision: "Analyze Decision",
      extract_context: "Extract Position",
      validate_context: "Validate Data",
      clarify_fields: "Clarify Fields",
      clarify_intent: "Clarify Intent",
      show_context: "Show Position",
      parse_context_decision: "Analyze Decision",
      edit_context: "Edit Position",
      next_context: "Next Position",
      show_final: "Final Review",
      parse_final_decision: "Final Decision",
      persist: "Save to DB",
      cancel: "Cancel",
    },
  },
  {
    name: "search-graph",
    importPath: "../src/facade/langGraph/search-graph/search-graph.js",
    title: "Search: Career Path Discovery",
    description:
      "Find waymates (same goal) and pathfinders (achieved goal). Explore → goal setting → filtering → DTW matching.",
    labels: {
      __start__: "Start",
      __end__: "End",
      load_context: "Load Profile",
      ask_adhoc_context: "Ask Quick Profile",
      confirm_adhoc_context: "Confirm Profile",
      check_goal: "Check Goal",
      explore: "Explore All",
      show_exploration: "Show Candidates",
      parse_search_intent: "Analyze Intent",
      clarify_intent: "Clarify",
      extract_goal: "Extract Goal",
      show_goal: "Show Goal",
      validate_goal: "Validate Goal",
      ask_after_validate: "Ask After Validation",
      load_existing_goal: "Load Saved Goal",
      set_goal: "Save Goal",
      ask_search_mode: "Choose Mode",
      delete_goal: "Delete Goal",
      search_waymates: "Find Waymates",
      search_pathfinders: "Find Pathfinders",
      show_results: "Show Results",
      apply_filters: "Apply Filters",
      generate_answer: "Generate Answer",
      show_answer: "Show Answer",
      cancel: "Cancel",
    },
  },
];

async function loadGraphModule(importPath: string): Promise<GraphModule> {
  return import(importPath);
}

const OUTPUT_DIR = "docs/graphs/technical";

function applyLabels(mermaid: string, labels: Record<string, string>): string {
  let result = mermaid;
  for (const [technical, business] of Object.entries(labels)) {
    const escaped = technical.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    // Stadium shape: ([<p>__start__</p>]) → (["Start"])
    result = result.replace(new RegExp(`\\(\\[<p>${escaped}</p>\\]\\)`, "g"), `(["${business}"])`);
    // Regular node: (gather_story) → ("Collect Story")
    result = result.replace(new RegExp(`\\(${escaped}\\)`, "g"), `("${business}")`);
  }
  return result;
}

async function exportGraph(config: GraphConfig): Promise<void> {
  const graphModule = await loadGraphModule(config.importPath);
  const builder = graphModule.createGraphBuilder();
  const compiled = builder.compile({ checkpointer: false });
  const graph = compiled.getGraph();
  let mermaid = graph.drawMermaid({ withStyles: true });

  if (config.labels) {
    mermaid = applyLabels(mermaid, config.labels);
  }

  const markdown = `# ${config.title}

> ${config.description}

\`\`\`mermaid
${mermaid}\`\`\`

---
*Generated by \`npm run graph\`. View interactively at [mermaid.live](https://mermaid.live).*
`;

  const outputPath = path.join(OUTPUT_DIR, `${config.name}.md`);
  writeFileSync(outputPath, markdown);
  console.log(`  ${config.name}.md`);
}

async function main(): Promise<void> {
  console.log(`\nExporting ${GRAPHS.length} LangGraph graphs to ${OUTPUT_DIR}/\n`);

  if (!existsSync(OUTPUT_DIR)) {
    mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  for (const config of GRAPHS) {
    await exportGraph(config);
  }

  console.log(`\n Done! View graphs in docs/graphs/ or at https://mermaid.live\n`);
}

await main();
