// AUTO-GENERATED by scripts/gen-preset-keys.ts
export const PRESET_KEYS = [
  "BALANCED",
  "FLEXIBLE",
  "GEO_FOCUSED",
  "SKILL_FOCUSED",
  "TARGET_FLEXIBLE",
] as const;

export type PresetName = (typeof PRESET_KEYS)[number];
