// AUTO-GENERATED by scripts/gen-user-keys.ts. Do not edit manually.
export const USER_KEYS = [
  "USER_001",
  "USER_002",
  "USER_004",
  "USER_007",
  "USER_009",
  "USER_015",
  "USER_021",
  "USER_026",
] as const;

export type UserKey = (typeof USER_KEYS)[number];
