// AUTO-GENERATED by scripts/gen-user-keys.ts. Do not edit manually.
export const USER_KEYS = [
  "user_001",
  "user_002",
  "user_004",
  "user_007",
  "user_009",
  "user_015",
  "user_021",
  "user_026",
] as const;

export type UserKey = (typeof USER_KEYS)[number];
